# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: BaseApp Local
    site_url: baseapp.local
    
    company_name: BaseApp Ltd
    admin_email: admin@baseapp.local
    
    support_name: BaseApp Support
    support_email: support@baseapp.local

production:
  <<: *local
  
staging:
  <<: *local

test:
  <<: *local
